name: initialsound
description: Chosung Quiz Game

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0+3

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^2.0.0
  cupertino_icons: ^1.0.2
  go_router: ^6.0.1
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_core: ^2.1.1  # Needed for Crashlytics below
  firebase_crashlytics: ^3.0.3  # Error reporting
  games_services: ^3.0.0  # Achievements and leaderboards
  font_awesome_flutter: ^10.3.0
  url_launcher: ^6.1.9
  easy_localization: ^3.0.0
  get: ^4.6.5
  firebase_storage: ^11.0.14
  firebase_app_check: ^0.1.1+12
  cached_network_image: ^3.2.3
  purchases_flutter: ^4.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  test: ^1.19.0
  flutter_neumorphic: ^3.0.3
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/gamebg/
    - assets/music/
    - assets/sfx/
    - assets/translations/

  fonts:
    - family: Retrosans
      fonts:
        - asset: assets/fonts/establish_Retrosans.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
