const gameRawData = [
  "movie",
  "우리 생애 최고의 순간",
  "kpop",
  "YES or YES: TWICE (트와이스)",
  "kpop",
  "갈색머리: 윤건",
  "movie",
  "탄생",
  "drama",
  "대박부동산",
  "proverb",
  "건드리지 않은 벌이 쏠까",
  "drama",
  "신분을 숨겨라",
  "kpop",
  "그런 일은: 박화요비",
  "movie",
  "명탐정 코난: 천공의 난파선",
  "kpop",
  "눈의 꽃: 박효신",
  "drama",
  "임협 헬퍼",
  "kpop",
  "백설공주를 사랑한 일곱번째 난장이: 쿨 (COOL)",
  "kpop",
  "Give It To Me: 씨스타",
  "proverb",
  "사위는 백년 손이요 며느리는 종신 식구라",
  "kpop",
  "Into the I-LAND: 아이유",
  "drama",
  "기쁜 소식",
  "movie",
  "럭키",
  "kpop",
  "여수 밤바다: 버스커 버스커",
  "movie",
  "손님",
  "movie",
  "다빈치 코드",
  "kpop",
  "Hip Song: 비",
  "movie",
  "레터스 투 줄리엣",
  "drama",
  "색소폰과 찹쌀떡",
  "drama",
  "그녀가 돌아왔다",
  "kpop",
  "못해 (Feat. 美): 포맨 (4MEN)",
  "drama",
  "N을 위하여",
  "kpop",
  "약속(Narration 강경헌): god",
  "kpop",
  "Ring My Bell (Feat. 나얼 Of Brown Eyed Soul): 다이나믹 듀오",
  "movie",
  "스위치",
  "drama",
  "어쩌다 발견한 하루",
  "kpop",
  "삐삐: 아이유",
  "kpop",
  "좋아: 민서 (MINSEO), 윤종신",
  "kpop",
  "밤편지: 아이유",
  "movie",
  "그림자 살인",
  "kpop",
  "꼭!: 김건모",
  "movie",
  "범죄와의 전쟁: 나쁜놈들 전성시대",
  "kpop",
  "사랑인가 봐: 멜로망스",
  "drama",
  "발칙하게 고고",
  "movie",
  "우주전쟁",
  "movie",
  "육혈포 강도단",
  "kpop",
  "Alcohol-Free: TWICE (트와이스)",
  "kpop",
  "취중고백: 김민석 (멜로망스)",
  "movie",
  "앰뷸런스",
  "movie",
  "댄싱퀸",
  "movie",
  "쩨쩨한 로맨스",
  "kpop",
  "Escape: 엄정화",
  "kpop",
  "벚꽃 엔딩: 버스커 버스커",
  "drama",
  "아소카",
  "proverb",
  "전 정이 구만리 같다",
  "kpop",
  "Hug: 동방신기 (TVXQ!)",
  "movie",
  "이스케이프 룸 2: 노 웨이 아웃",
  "drama",
  "다함께 차차차",
  "drama",
  "엄브렐러 아카데미",
  "movie",
  "아수라",
  "drama",
  "아머드 사우루스",
  "drama",
  "녹비홍수",
  "drama",
  "아르곤(MBC)",
  "proverb",
  "콩 심은 데 콩나고 팥 심은 데 팥난다",
  "drama",
  "군자맹",
  "kpop",
  "서쪽 하늘: 울랄라세션",
  "proverb",
  "값도 모르고 싸다고 한다",
  "drama",
  "루카: 더 비기닝",
  "drama",
  "예이 미! 주연 런던 팁튼",
  "drama",
  "리얼:타임:러브 PART 1",
  "proverb",
  "젖 먹던 힘이 다 든다",
  "kpop",
  "가시나: 선미",
  "movie",
  "나를 찾아줘",
  "movie",
  "논스톱",
  "kpop",
  "19금 니가 알던 내가 아냐 (Prod. By GRAY): 사이먼 도미닉, ONE, 지투 (G2), BewhY (비와이)",
  "drama",
  "마지스카 학원 4",
  "drama",
  "보스를 지켜라",
  "drama",
  "You Make Me Dance",
  "movie",
  "엑스맨 탄생: 울버린",
  "proverb",
  "마음은 굴뚝같다",
  "movie",
  "미션임파서블:고스트프로토콜",
  "kpop",
  "내 입술... 따뜻한 커피처럼: 샵",
  "movie",
  "고양이: 죽음을 보는 두 개의 눈",
  "movie",
  "언더 워터",
  "drama",
  "외과의사 봉달희",
  "proverb",
  "동네 송아지는 커도 송아지란다",
  "drama",
  "약속(2000년 드라마)",
  "drama",
  "유리구두",
  "kpop",
  "우리 헤어지자: 이승기",
  "drama",
  "기예르모 델 토로의 호기심의 방",
  "kpop",
  "가슴아 그만해: 엠씨더맥스 (M.C the MAX)",
  "kpop",
  "니가 있어야 할 곳: god",
  "proverb",
  "한 귀로 듣고 한 귀로 흘린다",
  "movie",
  "기억의 밤",
  "drama",
  "대진제국 3",
  "drama",
  "더 바이블",
  "movie",
  "아메리칸 스나이퍼",
  "drama",
  "머니게임(tvN)",
  "drama",
  "눈으로 말해요",
  "movie",
  "부당거래",
  "drama",
  "로맨스가 필요해 2012",
  "drama",
  "설련화",
  "kpop",
  "Tonight: 홍경민",
  "kpop",
  "Officially Missing You, Too: 긱스 (Geeks), 소유 (SOYOU)",
  "movie",
  "디워",
  "kpop",
  "고백: 양다일",
  "drama",
  "아직 최선을 다하지 않았을 뿐",
  "drama",
  "디데이",
  "movie",
  "제이슨 본",
  "kpop",
  "죽을만큼..: 오종혁",
  "drama",
  "국가대표 와이프",
  "movie",
  "23 아이덴티티",
  "drama",
  "원피스",
  "movie",
  "시크릿",
  "kpop",
  "하루: 김범수",
  "kpop",
  "천애 (For You): 이지훈",
  "kpop",
  "비: 폴킴",
  "proverb",
  "가마 속의 콩도 삶아야 먹는다",
  "movie",
  "그레이트 월",
  "proverb",
  "재주는 곰이 넘고 돈은 왕서방이 받는다",
  "drama",
  "울트라 세븐 X",
  "kpop",
  "그리움을 사랑한 가시나무: 테이",
  "drama",
  "돈의 화신",
  "drama",
  "사랑하기 좋은 날",
  "movie",
  "토르: 러브 앤 썬더",
  "drama",
  "2009 외인구단",
  "proverb",
  "물이 아니면 건너지 말고, 인정이 아니면 사귀지 말라",
  "kpop",
  "별처럼: 케이윌",
  "proverb",
  "개살구가 먼저 익는다",
  "kpop",
  "부메랑: 김건모",
  "movie",
  "연애의 온도",
  "kpop",
  "Indian Boy (Feat. 장근이, B.I): MC몽",
  "drama",
  "대왕 세종",
  "movie",
  "스파이더맨: 노 웨이 홈",
  "kpop",
  "떠나간다: 노을",
  "drama",
  "내 뒤에 테리우스",
  "kpop",
  "오래된 노래: 스탠딩 에그",
  "drama",
  "디 오퍼",
  "movie",
  "놉",
  "kpop",
  "strawberry moon: 아이유",
  "movie",
  "몬스터 vs 에이리언",
  "kpop",
  "봄이 좋냐??: 10CM",
  "movie",
  "기적",
  "kpop",
  "My Darling (End): 버즈",
  "movie",
  "트랜스포터-라스트 미션",
  "kpop",
  "연가: 유승준",
  "kpop",
  "Honeymoon: 유엔",
  "movie",
  "우아한 거짓말",
  "kpop",
  "Must Have Love: SG 워너비, 브라운아이드걸스",
  "kpop",
  "Shine: 슈가",
  "drama",
  "변호사 쉬헐크",
  "proverb",
  "아가리가 광주리만 해도 말을 못한다",
  "drama",
  "덱스터",
  "drama",
  "교도관 나오키",
  "movie",
  "레드 라이딩 후드",
  "drama",
  "미스코리아",
  "kpop",
  "구르미 그린 달빛: 거미",
  "drama",
  "꾸미는 사랑에는 이유가 있어",
  "drama",
  "스포트라이트",
  "drama",
  "난 왜 아빠랑 성이 달라?",
  "movie",
  "조커",
  "proverb",
  "귀에 걸면 귀걸이 코에 걸면 코걸이",
  "kpop",
  "늦은 밤 너의 집 앞 골목길에서: 노을",
  "movie",
  "극장판 엉덩이 탐정: 수플레 섬의 비밀",
  "kpop",
  "이바보: 원더걸스",
  "proverb",
  "이 없으면 잇몸으로 산다",
  "movie",
  "조이",
  "proverb",
  "열 손가락을 깨물어 안 아픈 손가락 없다",
  "drama",
  "미세스 캅",
  "kpop",
  "외국인의 고백: AKMU (악뮤)",
  "kpop",
  "Paris (Feat. Jisun of Loveholic): 에픽하이 (EPIK HIGH)",
  "proverb",
  "잔솔밭에서 바늘 찾기다",
  "kpop",
  "사랑이 올까요 (With 백지영): 마이티 마우스, 백지영",
  "kpop",
  "개미와 베짱이: 유리상자",
  "movie",
  "보스 베이비 2",
  "kpop",
  "정말 사랑했을까: 브라운 아이드 소울",
  "movie",
  "범블비",
  "drama",
  "내 눈에 콩깍지",
  "drama",
  "블랙의 신부",
  "movie",
  "아이스 에이지 3: 공룡시대",
  "kpop",
  "아무래도 난: 주시크 (Joosiq)",
  "movie",
  "너의 결혼식",
  "proverb",
  "길고 짧은 것은 대어 보아야 한다",
  "kpop",
  "19금 나 이런사람이야: DJ DOC",
  "movie",
  "마이 웨이",
  "proverb",
  "번갯불에 콩볶아 먹겠다",
  "drama",
  "꽃미남 라면가게",
  "movie",
  "특별수사: 사형수의 편지",
  "movie",
  "뜨거운 피",
  "kpop",
  "나쁜 여자야: FTISLAND (FT아일랜드)",
  "drama",
  "니가 깜짝 놀랄만한 얘기를 들려주마",
  "proverb",
  "산 밑 집에 방앗공이가 논다",
  "kpop",
  "19금 BORN HATER (Feat. 빈지노, 버벌진트, B.I, MINO, BOBBY): 에픽하이 (EPIK HIGH)",
  "kpop",
  "끝: 싸이 (PSY)",
  "drama",
  "갑동이",
  "kpop",
  "주저하는 연인들을 위해: 잔나비",
  "drama",
  "여자가 두번 화장할 때",
  "kpop",
  "I Promise You: 원티드, 이정",
  "kpop",
  "아무도 모르게 (Prod. by MC몽): 치타 (CHEETAH), 에일리(Ailee)",
  "kpop",
  "시간을 달려서 (Rough): 여자친구 (GFRIEND)",
  "kpop",
  "러시안 룰렛 (Russian Roulette): Red Velvet (레드벨벳)",
  "drama",
  "마지스카 학원 3",
  "kpop",
  "하루도 그대를 사랑하지 않은 적이 없었다: 임창정",
  "kpop",
  "최고의 행운: 첸 (CHEN)",
  "drama",
  "그래서 저는 픽했습니다",
  "drama",
  "머독 미스터리",
  "kpop",
  "Lie (Radio Ver.): 박화요비",
  "drama",
  "기묘한 이야기(시즌 3)",
  "movie",
  "우리 형",
  "kpop",
  "사뿐사뿐: AOA",
  "drama",
  "구여친클럽",
  "movie",
  "말레피센트",
  "kpop",
  "사랑이라 쓰고 아픔이라 부른다: 서인영",
  "movie",
  "인질",
  "kpop",
  "내 목소리 들리니: 벤",
  "movie",
  "가장 보통의 연애",
  "movie",
  "외계+인 1부",
  "kpop",
  "어떻게 이별까지 사랑하겠어, 널 사랑하는 거지: AKMU (악뮤)",
  "kpop",
  "헤어져줘서 고마워: 벤",
  "kpop",
  "Electric Shock: f(x)",
  "proverb",
  "세 살 버릇 여든까지 간다",
  "drama",
  "미스 마:복수의 여신",
  "kpop",
  "봄날: 아이",
  "kpop",
  "Let Me Dance: 렉시",
  "kpop",
  "Mr. Chu (On Stage): Apink (에이핑크)",
  "movie",
  "공작",
  "kpop",
  "흔한 이별: 허각",
  "drama",
  "울트라맨 데커",
  "kpop",
  "그대 돌아오면..: 거미",
  "drama",
  "태양속으로",
  "movie",
  "어쌔신 크리드",
  "movie",
  "너의 췌장을 먹고 싶어",
  "drama",
  "금혼령 조선 혼인 금지령",
  "drama",
  "무미랑전기",
  "movie",
  "로건",
  "drama",
  "전체 27개 문서",
  "kpop",
  "빌었어: 창모 (CHANGMO)",
  "proverb",
  "똥누고 밑 안 씻은 것 같다",
  "drama",
  "나의 너에게",
  "movie",
  "지.아이.조 2",
  "movie",
  "극장판 뽀로로와 친구들: 바이러스를 없애줘!",
  "drama",
  "외교관 쿠로다 코사쿠",
  "drama",
  "뜻밖의 히어로즈",
  "kpop",
  "바빠 (Bad Boy): 씨스타",
  "kpop",
  "사랑..다 거짓말: 린",
  "kpop",
  "아이스크림: MC몽",
  "drama",
  "마이티 덕스: 게임 체인저",
  "kpop",
  "출국 (出國): 하림",
  "movie",
  "신의 한 수",
  "movie",
  "황해",
  "movie",
  "샌 안드레아스",
  "drama",
  "고슴도치(베스트극장)",
  "kpop",
  "사랑하자: SG 워너비",
  "movie",
  "장수상회",
  "proverb",
  "호랑이 담배 필 적",
  "kpop",
  "Hello Hello: FTISLAND (FT아일랜드)",
  "drama",
  "우주전대 큐레인저",
  "kpop",
  "겨울사랑: The One (더원)",
  "drama",
  "신의 퀴즈",
  "kpop",
  "좋니: 윤종신",
  "proverb",
  "미운 놈 떡 하나 더 준다",
  "drama",
  "내 첫사랑을 너에게 바친다",
  "movie",
  "부라더",
  "kpop",
  "바보: 박효신",
  "kpop",
  "떠난 너: 김현정",
  "kpop",
  "이별후애(愛): 린애",
  "drama",
  "갤럭시 프로젝트",
  "kpop",
  "둘만의 세상으로 가: Crush",
  "drama",
  "루머의 루머의 루머",
  "kpop",
  "Better Together: SE7EN",
  "drama",
  "가면라이더 드라이브",
  "drama",
  "펀치(SBS)",
  "kpop",
  "너 하나야: 포맨 (4MEN)",
  "kpop",
  "Feeling: 김종국",
  "drama",
  "더 게임: 0시를 향하여",
  "movie",
  "나인",
  "movie",
  "타잔 3D",
  "kpop",
  "이 소설의 끝을 다시 써보려 해: 한동근",
  "movie",
  "도가니",
  "movie",
  "스타트렉 비욘드",
  "kpop",
  "너의 의미 (Feat. 김창완): 아이유",
  "kpop",
  "소나기 (주르르루): 버스커 버스커",
  "drama",
  "디셉션",
  "movie",
  "터닝메카드W: 블랙미러의 부활",
  "kpop",
  "사랑했어요 (Feat. 데니안): SG 워너비",
  "movie",
  "에베레스트",
  "kpop",
  "새 사랑: 송하예",
  "kpop",
  "Gee: 소녀시대 (GIRLS GENERATION)",
  "movie",
  "맨 인 더 다크",
  "movie",
  "앨빈과 슈퍼밴드2",
  "kpop",
  "사랑과 전쟁 (Narr. 하하): 다비치",
  "proverb",
  "잔고기가 가시는 세다",
  "movie",
  "메리와 마녀의 꽃",
  "drama",
  "굿 와이프",
  "movie",
  "고장난 론",
  "kpop",
  "LATATA: (여자)아이들",
  "drama",
  "사랑찬가",
  "drama",
  "건담 빌드 리얼",
  "movie",
  "조선명탐정 : 사라진 놉의 딸",
  "movie",
  "은밀하게 위대하게",
  "movie",
  "악의 연대기",
  "kpop",
  "너의 모든 순간: 성시경",
  "kpop",
  "사랑을 원해: 쿨 (COOL)",
  "kpop",
  "MY BAG: (여자)아이들",
  "movie",
  "슈퍼 배드",
  "kpop",
  "전화 한 번 못하니 (Feat. 미스에스 태혜영): 왁스",
  "drama",
  "더 폴리티션",
  "movie",
  "셔터 아일랜드",
  "drama",
  "블러드라인",
  "proverb",
  "아비만한 자식이 없다",
  "drama",
  "빌런즈",
  "kpop",
  "Love: 브라운아이드걸스",
  "drama",
  "결혼합시다(MBC)",
  "drama",
  "헬로! 발바리",
  "kpop",
  "View: SHINee (샤이니)",
  "kpop",
  "안좋을때 들으면 더 안좋은 노래: 형돈이와 대준이",
  "movie",
  "공공의 적 2",
  "movie",
  "카3: 새로운 도전",
  "movie",
  "사냥",
  "movie",
  "리오",
  "drama",
  "우리가족 마법사",
  "movie",
  "마녀(魔女) Part2. The Other One",
  "movie",
  "삼총사 3D",
  "proverb",
  "모난 돌이 정 맞는다",
  "movie",
  "모비우스",
  "drama",
  "60일 지정생존자",
  "drama",
  "두부 프로레슬링",
  "movie",
  "과속스캔들",
  "kpop",
  "까만안경 (Feat. Day Light): 이루, Daylight",
  "drama",
  "파워레인저 와일드포스",
  "drama",
  "더 캡처",
  "drama",
  "수리검전대 닌닌저",
  "kpop",
  "흩어진 나날들: 박효신",
  "proverb",
  "형만한 아우 없다",
  "drama",
  "그래서 나는 안티팬과 결혼했다",
  "kpop",
  "토요일밤에: 손담비",
  "drama",
  "슬기로운 생활 시리즈",
  "movie",
  "모가디슈",
  "drama",
  "사건번호 113",
  "movie",
  "페르시아의 왕자: 시간의 모래",
  "movie",
  "신비아파트: 금빛 도깨비와 비밀의 동굴",
  "kpop",
  "Hype boy: NewJeans",
  "drama",
  "드롭아웃",
  "movie",
  "대호",
  "drama",
  "일타 스캔들",
  "kpop",
  "Top Girl: 지나",
  "drama",
  "대한민국 변호사",
  "movie",
  "엔더스 게임",
  "kpop",
  "빚: 이수영",
  "movie",
  "침묵",
  "proverb",
  "끝도 갓도 없다",
  "proverb",
  "우선 먹기는 곶감이 달다",
  "kpop",
  "미워도 좋아: 별",
  "kpop",
  "일년이면: 휘성 (Realslow)",
  "kpop",
  "가슴이 아려와: 란 (RAN)",
  "drama",
  "리치 맨 푸어 우먼",
  "proverb",
  "첫 술에 배부르랴",
  "kpop",
  "사랑의 숲에서 길을 잃다 (Feat. 임창정): 제드",
  "kpop",
  "아마두 (feat.우원재, 김효은, 넉살, Huckleberry P): 염따, 딥플로우, 팔로알토 (Paloalto), The Quiett, 사이먼 도미닉",
  "drama",
  "너는 나의 봄",
  "drama",
  "인사이더",
  "drama",
  "최후의 변호인",
  "movie",
  "캐리와 슈퍼콜라",
  "drama",
  "오버 더 레인보우",
  "kpop",
  "아름다운 밤이야: 비스트",
  "kpop",
  "유리 (唯俚 - 비록 슬퍼진다 하더라도): 김정훈",
  "movie",
  "남과 여",
  "movie",
  "스텝 업 3D",
  "drama",
  "도둑놈 도둑님",
  "drama",
  "비질란테",
  "kpop",
  "제자리 걸음: 김종국",
  "drama",
  "미미쿠스",
  "proverb",
  "아는 길도 물어 가자",
  "drama",
  "전차남",
  "movie",
  "김종욱 찾기",
  "kpop",
  "주문-MIROTIC (Clean Ver.): 동방신기 (TVXQ!)",
  "movie",
  "메리다와 마법의 숲",
  "movie",
  "젠틀맨",
  "drama",
  "다섯 손가락",
  "drama",
  "두 번째 남편",
  "kpop",
  "After LIKE: IVE (아이브)",
  "kpop",
  "Its Raining: 비",
  "kpop",
  "헤어지러 가는 길 (Feat. 조권): 임정희",
  "kpop",
  "이노래: 2am",
  "movie",
  "소스 코드",
  "movie",
  "제보자",
  "movie",
  "토르: 라그나로크",
  "kpop",
  "바코드 (Prod. GroovyRoom): 김하온 (HAON), 빈첸",
  "kpop",
  "너도 그냥 날 놓아주면 돼: 윤건",
  "drama",
  "친구 우리들의 전설",
  "kpop",
  "클래식: KCM",
  "proverb",
  "제 배가 부르면 종 배고픈 줄 모른다",
  "drama",
  "오로라 공주",
  "movie",
  "컨저링3: 악마가 시켰다",
  "drama",
  "벼락맞은 문방구 2",
  "kpop",
  "No Make Up: Zion.T",
  "kpop",
  "HER: 블락비 (Block B)",
  "movie",
  "닌자터틀 : 어둠의 히어로",
  "kpop",
  "너의 곁으로: 조성모",
  "movie",
  "아더 크리스마스",
  "drama",
  "로드 넘버 원",
  "movie",
  "위자: 저주의 시작",
  "drama",
  "내 곁에 있어",
  "movie",
  "신들의 전쟁",
  "movie",
  "컨저링",
  "kpop",
  "어떤가요: 박화요비",
  "movie",
  "이스케이프 플랜",
  "drama",
  "미스 몬테크리스토",
  "proverb",
  "죽도 밥도 안 된다",
  "movie",
  "맨발의 꿈",
  "drama",
  "슈퍼대디 열",
  "kpop",
  "운전만해 (We Ride): 브레이브걸스",
  "movie",
  "브이아이피",
  "proverb",
  "어질병이 지랄병 된다",
  "proverb",
  "집에서 새는 바가지는 들에 가도 샌다",
  "drama",
  "래치드",
  "kpop",
  "Sweety: 샵",
  "movie",
  "극장판 주술회전 0",
  "drama",
  "복면검사",
  "movie",
  "곡성",
  "movie",
  "나는 전설이다",
  "kpop",
  "오늘 밤 (Feat. 배치기): 린",
  "movie",
  "스타워즈: 라스트 제다이",
  "drama",
  "7급 공무원",
  "movie",
  "천재 강아지 미스터 피바디",
  "proverb",
  "참새가 죽어도 짹한다",
  "movie",
  "덕혜옹주",
  "drama",
  "신화(SBS)",
  "kpop",
  "멋쟁이 신사: YG Family",
  "movie",
  "대배우",
  "drama",
  "더 뮤지컬",
  "movie",
  "분노의 질주: 홉스&쇼",
  "kpop",
  "만약에 말야 (전우성 Solo): 노을",
  "drama",
  "대군 - 사랑을 그리다",
  "proverb",
  "거지 발싸게 같다",
  "drama",
  "아들 녀석들",
  "kpop",
  "Boogie On & On: 빈지노 (Beenzino)",
  "movie",
  "인천상륙작전",
  "proverb",
  "부자는 망해도 삼 년 먹을 것이 있다",
  "movie",
  "신세계",
  "kpop",
  "Breathe: 미쓰에이",
  "drama",
  "모테키",
  "drama",
  "링크: 먹고 사랑하라 죽이게",
  "proverb",
  "도깨비 장난 같다",
  "drama",
  "그 남자 오수",
  "drama",
  "달이 뜨는 강",
  "kpop",
  "아니: 거미",
  "movie",
  "터미네이터: 다크 페이트",
  "kpop",
  "요즘 바쁜가봐: 2BIC(투빅)",
  "drama",
  "산부인과",
  "kpop",
  "또 다시 사랑: 임창정",
  "drama",
  "아름다운 그",
  "kpop",
  "CAFE: BIGBANG (빅뱅)",
  "movie",
  "베놈",
  "drama",
  "신사의 품격",
  "movie",
  "원피스 필름 골드",
  "movie",
  "노무현입니다",
  "drama",
  "그리고 베를린에서",
  "kpop",
  "가시리: SG 워너비, KCM",
  "movie",
  "밤의 여왕",
  "movie",
  "고질라 VS. 콩",
  "drama",
  "결혼해주세요",
  "kpop",
  "안녕: 폴킴",
  "movie",
  "마파도",
  "movie",
  "터보",
  "kpop",
  "화 (Feat. 진실 Of Mad Soul Child) (Fire): 매드클라운",
  "kpop",
  "연애특강 (FEAT. 한예슬): 마이티 마우스",
  "kpop",
  "맨정신: BIGBANG (빅뱅)",
  "kpop",
  "벚꽃 엔딩: 버스커 버스커",
  "proverb",
  "비단 옷 입고 밤 길 걷기",
  "drama",
  "스파이",
  "movie",
  "아이스 에이지 4: 대륙 이동설",
  "movie",
  "친구 2",
  "drama",
  "막돼먹은 영애씨 시즌14",
  "movie",
  "서복",
  "drama",
  "내 딸 금사월",
  "proverb",
  "장구치는 놈 따로 있고 고개 까딱이는 놈 따로 있나?",
  "movie",
  "수퍼 소닉2",
  "kpop",
  "한여름날의 꿈 (Duet With 옥주현): SG 워너비",
  "kpop",
  "Touch My Body: 씨스타",
  "proverb",
  "하룻밤을 자도 만리장성을 쌓는다",
  "drama",
  "장미의 전쟁(MBC)",
  "movie",
  "킹스 스피치",
  "movie",
  "링컨 차를 타는 변호사",
  "kpop",
  "IDOL: 방탄소년단",
  "proverb",
  "동네북이냐",
  "drama",
  "웨스트월드",
  "kpop",
  "그녀가 웃잖아....: 김형중",
  "kpop",
  "좋아: 민서 (MINSEO), 윤종신",
  "movie",
  "킹스맨: 퍼스트 에이전트",
  "drama",
  "아임 홈",
  "movie",
  "도리를 찾아서",
  "movie",
  "돈의 맛",
  "kpop",
  "시간이 흐른 뒤 (As Time Goes By): 윤미래",
  "drama",
  "불새 2020",
  "kpop",
  "부탁: 김원준",
  "movie",
  "유체이탈자",
  "kpop",
  "정말로 사랑한다면: 버스커 버스커",
  "kpop",
  "다시 만난 세계 (Into The New World): 소녀시대 (GIRLS GENERATION)",
  "movie",
  "데시벨",
  "movie",
  "마담 뺑덕",
  "drama",
  "맏이(JTBC)",
  "movie",
  "무뢰한",
  "movie",
  "강릉",
  "drama",
  "학교 2021",
  "kpop",
  "당신은 모르실거야 (CF - LIG 핑클편): 핑클 (Fin.K.L)",
  "movie",
  "콩: 스컬 아일랜드",
  "drama",
  "브리저튼",
  "movie",
  "마법사의 제자",
  "proverb",
  "고생 끝에 낙이 있다",
  "drama",
  "닥터 차정숙",
  "kpop",
  "통증: 거미",
  "kpop",
  "보라빛 밤 (pporappippam): 선미",
  "movie",
  "슈퍼 에이트",
  "kpop",
  "Ice Cream Cake: Red Velvet (레드벨벳)",
  "drama",
  "결혼계약",
  "proverb",
  "가자니 태산이요 돌아서자니 숭산이라",
  "movie",
  "호빗: 다섯 군대 전투",
  "kpop",
  "What is Love?: TWICE (트와이스)",
  "kpop",
  "보름달 (Feat. Lena): 선미",
  "movie",
  "리멤버",
  "movie",
  "동주",
  "proverb",
  "모처럼 태수가 되니 턱이 떨어진다",
  "drama",
  "부탁해요 캡틴",
  "kpop",
  "오랜만이야: 임창정",
  "kpop",
  "비와 당신: 이무진",
  "drama",
  "노다메 칸타빌레",
  "kpop",
  "취향저격: iKON",
  "drama",
  "몽화록",
  "kpop",
  "지 상세정보 페이지 이동:  편지",
  "movie",
  "청담보살",
  "kpop",
  "화장을 고치고: 왁스",
  "proverb",
  "산이 높아야 골이 깊다",
  "movie",
  "슬로우 비디오",
  "movie",
  "내부자들: 디 오리지널",
  "kpop",
  "분홍신: 아이유",
  "movie",
  "토탈 리콜",
  "movie",
  "더 배트맨",
  "kpop",
  "이제 나만 믿어요: 임영웅",
  "kpop",
  "Girls: aespa",
  "kpop",
  "소년이여: G-DRAGON",
  "drama",
  "소원을 말해봐",
  "movie",
  "빅매치",
  "drama",
  "스캔들: 매우 충격적이고 부도덕한 사건",
  "kpop",
  "가슴으로 외쳐 (Rap Feat. Rhymer): 먼데이 키즈 (Monday Kiz)",
  "drama",
  "떨리는 가슴",
  "drama",
  "더 킹 : 영원의 군주",
  "movie",
  "창궐",
  "drama",
  "디보스",
  "drama",
  "미생물",
  "movie",
  "방자전",
  "kpop",
  "기억상실: 거미",
  "drama",
  "아이돌 마스터.KR",
  "movie",
  "픽셀",
  "kpop",
  "잠이 오질 않네요: 장범준",
  "proverb",
  "고양이 쥐 생각",
  "movie",
  "더 임파서블",
  "kpop",
  "와줘..: SE7EN",
  "kpop",
  "여기까진가요: 플라워",
  "drama",
  "찔레꽃(KBS)",
  "movie",
  "내 생애 가장 아름다운 일주일",
  "movie",
  "투모로우",
  "drama",
  "내 아이디는 강남미인",
  "drama",
  "이 연애는 불가항력",
  "movie",
  "7번방의 선물",
  "drama",
  "Dr.깽",
  "drama",
  "황후의 품격",
  "drama",
  "광고천재 이태백",
  "movie",
  "월드 워 Z",
  "kpop",
  "다 줄꺼야: 이승기",
  "kpop",
  "우리가 이별할 때 (Duet 백지영): 소울스타 (SOULSTAR)",
  "kpop",
  "Counting Stars (Feat. Beenzino): BEO (비오)",
  "kpop",
  "삐삐: 아이유",
  "drama",
  "내 인생의 단비",
  "drama",
  "익스팬스",
  "drama",
  "연인들",
  "drama",
  "화려한 시절",
  "kpop",
  "A Real Man: 스윙스, 에일리(Ailee)",
  "movie",
  "메가마인드",
  "movie",
  "해피 데스데이",
  "movie",
  "레전드 오브 타잔",
  "kpop",
  "그대 돌아오면..: 거미",
  "movie",
  "블랙 팬서: 와칸다 포에버",
  "drama",
  "찬란한 유산",
  "proverb",
  "나귀는 제 귀 큰 줄을 모른다",
  "proverb",
  "비는 데는 무쇠도 녹는다",
  "movie",
  "쥬라기 월드: 도미니언",
  "proverb",
  "관 짜놓고 죽기를 기다린다",
  "movie",
  "순정",
  "kpop",
  "열 (Feat. Tablo): 이정(J.Lee)",
  "kpop",
  "Officially Missing You, Too: 긱스 (Geeks), 소유 (SOYOU)",
  "proverb",
  "가는 말에도 채찍질을 한다",
  "proverb",
  "누워 떡 먹기",
  "proverb",
  "꼬리가 길면 밟힌다",
  "movie",
  "언차티드",
  "kpop",
  "한번 단 한번: SE7EN",
  "drama",
  "가면라이더 히비키",
  "drama",
  "무법 변호사",
  "drama",
  "에덴의 동쪽",
  "kpop",
  "Sea Of Love: 플라이 투 더 스카이",
  "movie",
  "눈의 여왕5: 스노우 프린세스와 미러랜드의 비밀",
  "kpop",
  "Wanna: 카라",
  "kpop",
  "Boo: 아이유",
  "movie",
  "어린왕자",
  "movie",
  "스텝 업: 올 인",
  "movie",
  "앵커",
  "proverb",
  "떡 줄 사람은 생각하지도 않는데 김칫국부터 마신다",
  "movie",
  "시동",
  "kpop",
  "Loving U (러빙유): 씨스타",
  "kpop",
  "봄날: 방탄소년단",
  "movie",
  "컨저링 2",
  "movie",
  "도둑들",
  "movie",
  "계춘할망",
  "movie",
  "파파로티",
  "drama",
  "굿바이 미스터 블랙",
  "kpop",
  "Brand New: 신화",
  "kpop",
  "나를 봐: 이정(J.Lee)",
  "proverb",
  "늙은이 아이 된다",
  "drama",
  "마녀식당으로 오세요",
  "drama",
  "마이너리티 리포트",
  "proverb",
  "거짓말은 새끼를 친다",
  "drama",
  "스마일 어게인",
  "movie",
  "악녀",
  "proverb",
  "입이 여럿이면 무쇠도 녹인다",
  "drama",
  "공작도시",
  "proverb",
  "모진 놈 옆에 있다가 벼락 맞는다",
  "drama",
  "비밀의 여자",
  "proverb",
  "오뉴월 하루 볕이 무섭다",
  "kpop",
  "Good Day (Feat. 팔로알토) (Prod. 코드 쿤스트): pH-1, 키드밀리 (Kid Milli), 루피 (Loopy)",
  "movie",
  "몬스터 호텔",
  "kpop",
  "ID; Peace B: 보아 (BoA)",
  "drama",
  "아메리칸 호러 스토리/시즌 1",
  "drama",
  "그리고 아무도 없었다(2016년 드라마)",
  "movie",
  "의형제",
  "drama",
  "날 녹여주오",
  "kpop",
  "BAAAM (Feat. Muzie Of UV): 다이나믹 듀오",
  "drama",
  "여왕의 교실",
  "proverb",
  "기운이 세면 소가 왕 노릇할까",
  "kpop",
  "멋진헛간: 오대천왕 (정형돈, 밴드 혁오)",
  "movie",
  "테이큰 2",
  "kpop",
  "로보트: 서태지",
  "drama",
  "내일도 맑음",
  "movie",
  "킹콩",
  "movie",
  "맘마미아!",
  "kpop",
  "있어줘요: 장덕철",
  "proverb",
  "때리는 시어머니 보다 말리는 시누이가 더 밉다",
  "kpop",
  "그리워하다: 비투비",
  "kpop",
  "공감 (Feat. 서영은): 정준영",
  "drama",
  "폭룡전대 아바레인저",
  "kpop",
  "Heart Shaker: TWICE (트와이스)",
  "drama",
  "아메리칸즈",
  "drama",
  "마블 디펜더스",
  "kpop",
  "LOVE DIVE: IVE (아이브)",
  "proverb",
  "서울 가서 김서방 집 찾기",
  "movie",
  "라스트 갓파더",
  "kpop",
  "I My Me Mine: 4minute",
  "movie",
  "공자 춘추전국시대",
  "movie",
  "발레리안: 천 개 행성의 도시",
  "drama",
  "온리유",
  "kpop",
  "고백: 이승철",
  "proverb",
  "값 싼 것이 비지떡",
  "movie",
  "백야행",
  "movie",
  "스카이스크래퍼",
  "proverb",
  "벌거벗고 환도 찬다",
  "kpop",
  "끝사랑: 김범수",
  "movie",
  "블랙 스완",
  "kpop",
  "Heartbeat: 2PM",
  "movie",
  "써로게이트",
  "proverb",
  "임도 보고 뽕도 딴다",
  "movie",
  "찌라시: 위험한 소문",
  "movie",
  "루카",
  "kpop",
  "Ordinary People: SG 워너비",
  "kpop",
  "오늘따라 보고싶어서 그래: 다비치",
  "kpop",
  "나 어떡해: 베이비복스",
  "movie",
  "닌자 어쌔신",
  "kpop",
  "센치해: WINNER",
  "kpop",
  "아가씨와 건달들: 쿨 (COOL)",
  "drama",
  "독신천하",
  "movie",
  "동감",
  "drama",
  "새 엄마",
  "kpop",
  "쏘쏘: 백아연",
  "kpop",
  "너라고 (Its You): SUPER JUNIOR (슈퍼주니어)",
  "movie",
  "캡틴 마블",
  "movie",
  "빅",
  "kpop",
  "안녕: 이소라",
  "movie",
  "아이들...",
  "movie",
  "더 박스",
  "drama",
  "매일 그대와",
  "drama",
  "남자의 향기",
  "drama",
  "황금빛 내 인생",
  "proverb",
  "호박에 침주기",
  "movie",
  "탐정 : 더 비기닝",
  "movie",
  "보이스",
  "drama",
  "마인드헌터",
  "kpop",
  "기도: 정일영",
  "drama",
  "거짓말의 거짓말",
  "movie",
  "투사부일체",
  "kpop",
  "너를 만나: 폴킴",
  "kpop",
  "붉은 노을: BIGBANG (빅뱅)",
  "kpop",
  "내가 아니라도: 주호",
  "kpop",
  "Music: 바다 (BADA)",
  "proverb",
  "공연한 제사 지내고 어물값에 졸린다",
  "drama",
  "슬픔이여 안녕",
  "movie",
  "성난 변호사",
  "kpop",
  "Mr. Flower: 조성모",
  "drama",
  "너 미워! 줄리엣",
  "proverb",
  "그 아비에 그 아들",
  "kpop",
  "그 남자 그 여자: 포맨 (4MEN), 미(MIIII)",
  "proverb",
  "남이 장에 간다고 하니 거름지고 나선다",
  "drama",
  "나만의 당신",
  "drama",
  "아줌마가 간다",
  "drama",
  "소풍가는 여자",
  "movie",
  "미쓰백",
  "drama",
  "단팥빵",
  "drama",
  "울트라맨 블레이저",
  "movie",
  "새미의 어드벤쳐 2",
  "movie",
  "프리 가이",
  "drama",
  "검법남녀",
  "movie",
  "우리들의 행복한 시간",
  "movie",
  "분노의 질주: 언리미티드",
  "kpop",
  "하루 하루: BIGBANG (빅뱅)",
  "proverb",
  "참고 사는 것이 인생이다",
  "movie",
  "2012",
  "kpop",
  "빨개요: 현아",
  "drama",
  "달의 연인 - 보보경심 려",
  "kpop",
  "그 여름을 틀어줘: 싹쓰리 (유두래곤, 린다G, 비룡)",
  "drama",
  "보석비빔밥",
  "kpop",
  "다시 난, 여기: 백예린 (Yerin Baek)",
  "kpop",
  "사랑이었다 (Feat. 루나 of f(x)): 지코 (ZICO)",
  "kpop",
  "솔직하게 말해서 나: 김나영",
  "movie",
  "프린스 챠밍",
  "movie",
  "반가운 살인자",
  "movie",
  "스파이",
  "drama",
  "라이프",
  "proverb",
  "잘 되면 제 탓이요 못되면 조상 탓이다",
  "movie",
  "화이트 하우스 다운",
  "movie",
  "하루",
  "movie",
  "어바웃 타임",
  "drama",
  "로봇이 아니야",
  "kpop",
  "오늘부터 우리는 (Me Gustas Tu): 여자친구 (GFRIEND)",
  "movie",
  "증인",
  "kpop",
  "싫다: 백지영",
  "kpop",
  "사랑하나요!?: 이승환",
  "movie",
  "신이 보낸 사람",
  "kpop",
  "오늘도 빛나는 너에게 (To You My Light) (Feat.이라온): 마크툽 (MAKTUB)",
  "kpop",
  "바람기억: 나얼",
  "movie",
  "불릿 트레인",
  "movie",
  "버닝",
  "drama",
  "이두나!",
  "drama",
  "원한 해결 사무소",
  "movie",
  "감시자들",
  "kpop",
  "기억을 걷는 시간: 넬 (NELL)",
  "movie",
  "임금님의 사건수첩",
  "drama",
  "소방서 옆 경찰서",
  "drama",
  "마사지 탐정 죠",
  "drama",
  "경경일상",
  "movie",
  "독전",
  "movie",
  "핑크퐁 시네마 콘서트 2: 원더스타 콘서트 대작전",
  "movie",
  "내 머리 속의 지우개",
  "movie",
  "브레이킹 던 part2",
  "movie",
  "방가? 방가!",
  "proverb",
  "삼십육계에 줄행랑이 제일이다",
  "drama",
  "대연애~나를 잊을 너와",
  "movie",
  "신과함께-인과 연",
  "kpop",
  "와: 이정현",
  "drama",
  "그 땅에는 신이 없다 - Godless",
  "drama",
  "굿 닥터",
  "drama",
  "결혼백서",
  "drama",
  "지금도 마로니에는",
  "drama",
  "너를 기억해",
  "drama",
  "다시 첫사랑",
  "kpop",
  "너를 위해: 임재범",
  "drama",
  "나쁜엄마",
  "kpop",
  "별이 빛나는 밤: 마마무 (Mamamoo)",
  "movie",
  "엑스맨: 데이즈 오브 퓨처 패스트",
  "drama",
  "학교 3",
  "proverb",
  "소매 긴 김에 춤춘다",
  "drama",
  "사랑을 예약하세요",
  "drama",
  "오늘의 웹툰",
  "drama",
  "그녀의 사생활",
  "kpop",
  "크레용 (Crayon): G-DRAGON",
  "drama",
  "백스테이지",
  "movie",
  "마음이2",
  "movie",
  "분노의 질주: 더 오리지널",
  "drama",
  "일지매(2008년 드라마)",
  "drama",
  "호크아이",
  "proverb",
  "꿩 잡는 것이 매다",
  "movie",
  "고령화 가족",
  "movie",
  "분노의 질주: 더 세븐",
  "movie",
  "로그 원: 스타워즈 스토리",
  "drama",
  "내일은 맑음(2000년 드라마)",
  "movie",
  "오늘 밤, 세계에서 이 사랑이 사라진다 해도",
  "kpop",
  "폭풍: SG 워너비",
  "kpop",
  "19금 냉탕에 상어 (Feat. 블랙넛): 수퍼비 (SUPERBEE)",
  "kpop",
  "Artist: 지코 (ZICO)",
  "kpop",
  "괜찮아 사랑이야: 다비치",
  "movie",
  "애나벨 : 인형의 주인",
  "kpop",
  "세 사람 (With 성시경): 토이",
  "drama",
  "밤에 피는 꽃",
  "proverb",
  "말은 할수록 늘고, 되질은 할수록 준다",
  "movie",
  "오블리비언",
  "drama",
  "신센구미!",
  "drama",
  "오징어 게임",
  "movie",
  "다이 하드 4 : 죽어도 산다",
  "drama",
  "수사반장 1963",
  "drama",
  "가두리횟집",
  "kpop",
  "Heartbreaker: G-DRAGON",
  "drama",
  "매직키드 마수리",
  "kpop",
  "숨: 박효신",
  "movie",
  "이상한 나라의 앨리스",
  "kpop",
  "Apple (Feat. 박재범): 가인",
  "movie",
  "신데렐라",
  "drama",
  "나와 그녀와 그녀가 사는 길",
  "proverb",
  "자식 겉 낳지 속은 못 낳는다",
  "drama",
  "명랑소녀 성공기",
  "movie",
  "엘리시움",
  "movie",
  "시간 여행자의 아내",
  "drama",
  "도로시를 찾아라",
  "kpop",
  "내 손을 잡아: 아이유",
  "proverb",
  "드문드문 걸어도 황소걸음이다",
  "drama",
  "다운튼 애비",
  "movie",
  "볼트",
  "kpop",
  "사랑 먼지: 버블 시스터즈",
  "drama",
  "미스 리플리",
  "drama",
  "무림학교",
  "kpop",
  "이러지마 제발 (Please Dont...): 케이윌",
  "proverb",
  "내 발등의 불을 꺼야 아비 발등의 불을 끈다",
  "movie",
  "장산범",
  "drama",
  "서른 아홉",
  "kpop",
  "Give Love: AKMU (악뮤)",
  "kpop",
  "삐리빠빠: 나르샤 (Brown Eyed Girls)",
  "kpop",
  "너를 사랑해: 윤미래",
  "drama",
  "나쁜사랑",
  "kpop",
  "어떻게 지내: Crush",
  "drama",
  "사랑의 28법칙",
  "kpop",
  "포장마차: 황인욱",
  "movie",
  "좋은 친구들",
  "drama",
  "논스톱5",
  "drama",
  "구미호뎐",
  "proverb",
  "젊어 고생은 사서도 한다",
  "movie",
  "장르만 로맨스",
  "movie",
  "소셜 네트워크",
  "drama",
  "내셔널 트레져: 숨겨진 이야기",
  "movie",
  "그래비티",
  "drama",
  "고교처세왕",
  "drama",
  "내 사위의 여자",
  "kpop",
  "보통날: god",
  "drama",
  "보통의 연애",
  "kpop",
  "나를 외치다: 마야",
  "drama",
  "부암동 복수자들",
  "kpop",
  "너를 만나: 폴킴",
  "proverb",
  "오리보고 십리 간다",
  "proverb",
  "구관이 명관이다",
  "movie",
  "가디언의 전설",
  "movie",
  "토이 스토리 3",
  "movie",
  "우리는 형제입니다",
  "drama",
  "아이좀비",
  "kpop",
  "나만 안되는 연애: 볼빨간사춘기",
  "drama",
  "농부사관학교 2",
  "kpop",
  "한여름밤의 꿀: San E (산이), 레이나 (Raina)",
  "drama",
  "블러드",
  "drama",
  "편의점 샛별이",
  "drama",
  "홍국영",
  "movie",
  "바다 탐험대 옥토넛 : 탐험선 대작전",
  "kpop",
  "1,2,3,4 (원,투,쓰리,포): 이하이",
  "movie",
  "캡틴 아메리카: 시빌 워",
  "movie",
  "인셉션",
  "drama",
  "올드미스 다이어리",
  "drama",
  "너의 시간 속으로",
  "movie",
  "스파이럴",
  "drama",
  "스틸러: 일곱 개의 조선통보",
  "movie",
  "라야와 마지막 드래곤",
  "drama",
  "멋진 친구들 2",
  "movie",
  "극장판 안녕 자두야",
  "kpop",
  "술이 달다 (Feat. Crush): 에픽하이 (EPIK HIGH)",
  "drama",
  "유리의 성(2008)",
  "drama",
  "간니발",
  "kpop",
  "호랑수월가: 탑현",
  "kpop",
  "거북이: 다비치",
  "movie",
  "공범",
  "proverb",
  "도둑집 개는 짖지 않는다",
  "drama",
  "아내와 여자",
  "drama",
  "사랑은 노래를 타고",
  "kpop",
  "그대는 눈물겹다: 엠씨더맥스 (M.C the MAX)",
  "drama",
  "보라! 데보라",
  "drama",
  "나기의 휴식",
  "kpop",
  "기다렸다 가: 다이나믹 듀오, 첸 (CHEN)",
  "proverb",
  "비단 옷을 입으면 어깨가 올라간다",
  "drama",
  "1%의 어떤 것(2003)",
  "kpop",
  "친구라도 될 걸 그랬어: 거미",
  "movie",
  "아바타",
  "movie",
  "여고괴담 5",
  "movie",
  "고산자, 대동여지도",
  "proverb",
  "물불을 가리지 않는다",
  "drama",
  "당신과 나의 거리 63피트",
  "proverb",
  "꿩 먹고 알 먹는다",
  "movie",
  "베스트셀러",
  "drama",
  "크리스마스에 눈이 올까요?",
  "kpop",
  "동경: 박효신",
  "drama",
  "베이비(이탈리아 드라마)",
  "proverb",
  "하늘보고 침뱉기다",
  "drama",
  "몬스타",
  "drama",
  "구경이",
  "proverb",
  "화약을 지고 불에 들어간다",
  "kpop",
  "체념 後(후): 빅마마",
  "drama",
  "국민사형투표",
  "kpop",
  "Ah Yeah: EXID",
  "kpop",
  "우연히 봄: 로꼬, 유주 (YUJU)",
  "drama",
  "내일도 칸타빌레",
  "movie",
  "인생은 뷰티풀: 비타돌체",
  "drama",
  "시작의 노래",
  "kpop",
  "나의 사춘기에게: 볼빨간사춘기",
  "kpop",
  "풍변기곡(風變旗曲): 룰라",
  "kpop",
  "놀러와: 러브홀릭",
  "movie",
  "널 기다리며",
  "drama",
  "변호사들",
  "kpop",
  "안녕이란 말 대신: 비",
  "drama",
  "마이걸",
  "kpop",
  "UPT Paradoxxx: 업타운",
  "drama",
  "마녀의 발견",
  "drama",
  "칼잡이 오수정",
  "drama",
  "러브 어게인",
  "kpop",
  "나에게로 떠나는 여행: 버즈",
  "kpop",
  "Bravo, My Life!: 봄여름가을겨울",
  "drama",
  "그대 웃어요",
  "movie",
  "짱구는 못말려 극장판: 나의 이사 이야기 선인장 대습격",
  "movie",
  "몬스터 대학교",
  "movie",
  "퍼시 잭슨과 괴물의 바다",
  "movie",
  "꾼",
  "proverb",
  "가까운 남이 먼 친척보다 낫다",
  "drama",
  "그녀는 예뻤다",
  "drama",
  "연애조작단; 시라노",
  "movie",
  "올빼미",
  "kpop",
  "Back To The Real Life: 윤상",
  "movie",
  "PMC: 더 벙커",
  "drama",
  "하얀거탑",
  "movie",
  "아저씨",
  "movie",
  "남자사용설명서",
  "proverb",
  "나라 하나에 임금이 셋이다",
  "movie",
  "엑스맨: 퍼스트 클래스",
  "movie",
  "파라노말 액티비티",
  "kpop",
  "Savage: aespa",
  "drama",
  "신부와 아빠",
  "kpop",
  "그대 내게 다시: 럼블피쉬",
  "movie",
  "적인걸: 측천무후의 비밀",
  "movie",
  "익스펜더블",
  "kpop",
  "모든 날, 모든 순간 (Every day, Every Moment): 폴킴",
  "proverb",
  "족제비도 낯짝이 있다",
  "movie",
  "여배우들",
  "drama",
  "나는 네가 지난 여름에 한 일을 알고 있다",
  "kpop",
  "Goodbye: 이수영",
  "movie",
  "더 킬러: 죽어도 되는 아이",
  "kpop",
  "Windy: 유진",
  "kpop",
  "So Fresh (Feat. 김태우) (위대한 캣츠비 OST 삽입곡): MC몽",
  "movie",
  "그것",
  "drama",
  "조강지처 클럽(SBS)",
  "movie",
  "아바타 리마스터링",
  "kpop",
  "발자국: 먼데이 키즈 (Monday Kiz)",
  "movie",
  "타이탄",
  "proverb",
  "노루 잠자듯 한다",
  "drama",
  "여왕의 교실(MBC)",
  "drama",
  "사랑해서 남주나",
  "kpop",
  "Sixth Sense: 브라운아이드걸스",
  "drama",
  "상류사회",
  "kpop",
  "배운게 사랑이라: 디셈버",
  "drama",
  "팔콘과 윈터 솔져",
  "movie",
  "화이트: 저주의 멜로디",
  "kpop",
  "가슴이 뛴다: 케이윌",
  "kpop",
  "그대가 그대를: 이승환",
  "proverb",
  "썩어도 준치",
  "movie",
  "회사원",
  "drama",
  "첫사랑(SBS)",
  "kpop",
  "우린 어쩌다 헤어진 걸까: 허각",
  "drama",
  "가을에 만난 남자",
  "drama",
  "연인(2006년 드라마)",
  "kpop",
  "Blueming: 아이유",
  "movie",
  "헝거게임: 모킹제이",
  "proverb",
  "산 호랑이 눈썹",
  "movie",
  "무적자",
  "movie",
  "소녀괴담",
  "movie",
  "박열",
  "drama",
  "베리 잉글리시 스캔들",
  "movie",
  "압꾸정",
  "movie",
  "레지던트 이블: 파멸의 날",
  "movie",
  "슈렉2",
  "movie",
  "화차",
  "proverb",
  "저녁 굶은 시어미 꼴 같다",
  "proverb",
  "뜨고도 못 보는 당달 봉사",
  "drama",
  "겨우 서른",
  "drama",
  "천년지애",
  "kpop",
  "후회는 없어 (Feat. 베이지): 노블레스",
  "movie",
  "마다가스카 2",
  "movie",
  "닥터 스트레인지",
  "movie",
  "나의 사랑 나의 신부",
  "movie",
  "개구쟁이 스머프 2",
  "proverb",
  "냉수 먹고 된똥 눈다",
  "drama",
  "착한여자 백일홍",
  "proverb",
  "학도 아니고 봉도 아니고",
  "movie",
  "퍼시픽 림: 업라이징",
  "drama",
  "이별에 대처하는 우리의 자세",
  "movie",
  "차우",
  "kpop",
  "사건의 지평선: 윤하 (YOUNHA)",
  "movie",
  "한반도",
  "drama",
  "루루공주",
  "drama",
  "최강칠우",
  "proverb",
  "좁쌀영감이다",
];
